# Generated by Django 2.0.4 on 2018-05-23 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20180523_2352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='is_banner',
        ),
    ]
