# Generated by Django 2.0.4 on 2018-07-03 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_course_is_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerCourse',
            fields=[
            ],
            options={
                'verbose_name': '轮播课程',
                'verbose_name_plural': '轮播课程',
                'proxy': True,
                'indexes': [],
            },
            bases=('courses.course',),
        ),
        migrations.RemoveField(
            model_name='course',
            name='detail',
        ),
    ]
