# Generated by Django 2.0.4 on 2018-07-03 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_course_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='detail',
        ),
    ]
