# Generated by Django 2.0.4 on 2018-06-18 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0004_auto_20180520_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecomments',
            name='image',
            field=models.ImageField(default='image/default.png', upload_to='image/%Y/%m'),
        ),
    ]
