# Generated by Django 2.0.4 on 2018-06-18 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0005_coursecomments_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursecomments',
            name='image',
        ),
    ]
